package ru.harimasa.viewmodel.config;

import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.FloatSliderControllerBuilder;
import dev.isxander.yacl3.api.controller.IntegerSliderControllerBuilder;
import dev.isxander.yacl3.api.controller.TickBoxControllerBuilder;
import dev.isxander.yacl3.config.v2.api.ConfigClassHandler;
import dev.isxander.yacl3.config.v2.api.serializer.GsonConfigSerializerBuilder;
import dev.isxander.yacl3.gui.controllers.cycling.EnumController;
import net.fabricmc.loader.api.FabricLoader;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.text.Text;

import java.text.DecimalFormat;

public class VMScreen {
    public static final DecimalFormat FORMAT = new DecimalFormat("#.##");

    public static final ConfigClassHandler<VMConfig> CONFIG = ConfigClassHandler.createBuilder(VMConfig.class)
            .serializer(config -> GsonConfigSerializerBuilder.create(config)
                    .setPath(FabricLoader.getInstance().getConfigDir().resolve("viewmodel.json"))
                    .build())
            .build();

    @SuppressWarnings("deprecation")
    public static Screen screen(Screen parent) {
        return YetAnotherConfigLib.create(CONFIG, ((defaults, config, builder) -> builder
                .title(Text.translatable("viewmodel.title"))
                .category(ConfigCategory.createBuilder()
                        .name(Text.translatable("viewmodel.category.general"))
                        .option(Option.createBuilder(boolean.class)
                                .name(Text.translatable("viewmodel.category.general.enabled"))
                                .description(OptionDescription.of(Text.translatable("viewmodel.category.general.enabled.desc")))
                                .binding(defaults.enable, () -> config.enable, newVal -> config.enable = newVal)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("viewmodel.category.general.group.mainhand"))
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("viewmodel.category.general.mainScale"))
                                        .description(OptionDescription.of(Text.translatable("viewmodel.category.general.mainScale.desc")))
                                        .binding(1f, () -> config.mainScale, newVal -> config.mainScale = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(0.1f, 3f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("viewmodel.category.general.posX"))
                                        .description(OptionDescription.of(Text.translatable("viewmodel.category.general.posX.desc")))
                                        .binding(0f, () -> config.posMainX, newVal -> config.posMainX = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-3f, 3f)
                                                .step(0.05f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("viewmodel.category.general.posY"))
                                        .description(OptionDescription.of(Text.translatable("viewmodel.category.general.posY.desc")))
                                        .binding(0f, () -> config.posMainY, newVal -> config.posMainY = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-3f, 3f)
                                                .step(0.05f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("viewmodel.category.general.posZ"))
                                        .description(OptionDescription.of(Text.translatable("viewmodel.category.general.posZ.desc")))
                                        .binding(0f, () -> config.posMainZ, newVal -> config.posMainZ = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-3f, 3f)
                                                .step(0.05f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("viewmodel.category.general.rotX"))
                                        .description(OptionDescription.of(Text.translatable("viewmodel.category.general.rotX.desc")))
                                        .binding(0f, () -> config.rotMainX, newVal -> config.rotMainX = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-180f, 180f)
                                                .step(0.05f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("viewmodel.category.general.rotY"))
                                        .description(OptionDescription.of(Text.translatable("viewmodel.category.general.rotY.desc")))
                                        .binding(0f, () -> config.rotMainY, newVal -> config.rotMainY = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-180f, 180f)
                                                .step(0.05f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("viewmodel.category.general.rotZ"))
                                        .description(OptionDescription.of(Text.translatable("viewmodel.category.general.rotZ.desc")))
                                        .binding(0f, () -> config.rotMainZ, newVal -> config.rotMainZ = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-180f, 180f)
                                                .step(0.05f))
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("viewmodel.category.general.group.offhand"))
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("viewmodel.category.general.offScale"))
                                        .description(OptionDescription.of(Text.translatable("viewmodel.category.general.offScale.desc")))
                                        .binding(1f, () -> config.offScale, newVal -> config.offScale = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(0.1f, 3f)
                                                .step(0.01f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("viewmodel.category.general.posX"))
                                        .description(OptionDescription.of(Text.translatable("viewmodel.category.general.posX.desc")))
                                        .binding(0f, () -> config.posOffX, newVal -> config.posOffX = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-3f, 3f)
                                                .step(0.05f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("viewmodel.category.general.posY"))
                                        .description(OptionDescription.of(Text.translatable("viewmodel.category.general.posY.desc")))
                                        .binding(0f, () -> config.posOffY, newVal -> config.posOffY = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-3f, 3f)
                                                .step(0.05f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("viewmodel.category.general.posZ"))
                                        .description(OptionDescription.of(Text.translatable("viewmodel.category.general.posZ.desc")))
                                        .binding(0f, () -> config.posOffZ, newVal -> config.posOffZ = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-3f, 3f)
                                                .step(0.05f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("viewmodel.category.general.rotX"))
                                        .description(OptionDescription.of(Text.translatable("viewmodel.category.general.rotX.desc")))
                                        .binding(0f, () -> config.rotOffX, newVal -> config.rotOffX = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-180f, 180f)
                                                .step(0.05f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("viewmodel.category.general.rotY"))
                                        .description(OptionDescription.of(Text.translatable("viewmodel.category.general.rotY.desc")))
                                        .binding(0f, () -> config.rotOffY, newVal -> config.rotOffY = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-180f, 180f)
                                                .step(0.05f))
                                        .build())
                                .option(Option.createBuilder(float.class)
                                        .name(Text.translatable("viewmodel.category.general.rotZ"))
                                        .description(OptionDescription.of(Text.translatable("viewmodel.category.general.rotZ.desc")))
                                        .binding(0f, () -> config.rotOffZ, newVal -> config.rotOffZ = newVal)
                                        .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                                .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                                .range(-180f, 180f)
                                                .step(0.05f))
                                        .build())
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Text.translatable("viewmodel.category.swinganimation"))
                        .option(Option.createBuilder(boolean.class)
                                .name(Text.translatable("viewmodel.category.swinganimation.enable"))
                                .description(OptionDescription.of(Text.translatable("viewmodel.category.swinganimation.enabled.desc")))
                                .binding(defaults.swinganimEnable, () -> config.swinganimEnable, newVal -> config.swinganimEnable = newVal)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.createBuilder(boolean.class)
                                .name(Text.translatable("viewmodel.category.swinganimation.slowEnable"))
                                .description(OptionDescription.of(Text.translatable("viewmodel.category.swinganimation.slowEnable.desc")))
                                .binding(defaults.slowAnim, () -> config.slowAnim, newVal -> config.slowAnim = newVal)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.createBuilder(int.class)
                                .name(Text.translatable("viewmodel.category.swinganimation.slowAnimValue"))
                                .description(OptionDescription.of(Text.translatable("viewmodel.category.swinganimation.slowAnimValue.desc")))
                                .binding(12, () -> config.slowAnimValue, newVal -> config.slowAnimValue = newVal)
                                .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                                        .range(0, 50)
                                        .step(1))
                                .build())
                        .option(Option.<VMConfig.Templates>createBuilder()
                                .name(Text.translatable("viewmodel.category.swinganimation.templates"))
                                .binding(defaults.enumOption, () -> config.enumOption, (value) -> config.enumOption = value)
                                .customController(opt -> new EnumController<>(opt, VMConfig.Templates.class))
                                .build())
                        .build())
                .category(ConfigCategory.createBuilder()
                        .name(Text.translatable("viewmodel.category.advanced"))
                        .option(Option.createBuilder(boolean.class)
                                .name(Text.translatable("viewmodel.category.advanced.enable"))
                                .description(OptionDescription.of(Text.translatable("viewmodel.category.advanced.enable.desc")))
                                .binding(defaults.rotAnimEnable, () -> config.rotAnimEnable, newVal -> config.rotAnimEnable = newVal)
                                .controller(TickBoxControllerBuilder::create)
                                .build())
                        .option(Option.createBuilder(float.class)
                                .name(Text.translatable("viewmodel.category.advanced.speed"))
                                .description(OptionDescription.of(Text.translatable("viewmodel.category.advanced.speed.desc")))
                                .binding(1f, () -> config.rotAnimSpeed, newVal -> config.rotAnimSpeed = newVal)
                                .controller(opt -> FloatSliderControllerBuilder.create(opt)
                                        .valueFormatter(value -> Text.literal(FORMAT.format(value)))
                                        .range(0.1f, 5f)
                                        .step(0.1f))
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("viewmodel.category.advanced.group.mainhand"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("viewmodel.category.advanced.group.general.function.rotX"))
                                        .description(OptionDescription.of(Text.translatable("viewmodel.category.advanced.group.general.function.rotX")))
                                        .binding(defaults.rotAnimMainX, () -> config.rotAnimMainX, newVal -> config.rotAnimMainX = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("viewmodel.category.advanced.group.general.function.rotY"))
                                        .description(OptionDescription.of(Text.translatable("viewmodel.category.advanced.group.general.function.rotY")))
                                        .binding(defaults.rotAnimMainY, () -> config.rotAnimMainY, newVal -> config.rotAnimMainY = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("viewmodel.category.advanced.group.general.function.rotZ"))
                                        .description(OptionDescription.of(Text.translatable("viewmodel.category.advanced.group.general.function.rotZ")))
                                        .binding(defaults.rotAnimMainZ, () -> config.rotAnimMainZ, newVal -> config.rotAnimMainZ = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        .group(OptionGroup.createBuilder()
                                .name(Text.translatable("viewmodel.category.advanced.group.offhand"))
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("viewmodel.category.advanced.group.general.function.rotX"))
                                        .description(OptionDescription.of(Text.translatable("viewmodel.category.advanced.group.general.function.rotX")))
                                        .binding(defaults.rotAnimOffX, () -> config.rotAnimOffX, newVal -> config.rotAnimOffX = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("viewmodel.category.advanced.group.general.function.rotY"))
                                        .description(OptionDescription.of(Text.translatable("viewmodel.category.advanced.group.general.function.rotY")))
                                        .binding(defaults.rotAnimOffY, () -> config.rotAnimOffY, newVal -> config.rotAnimOffY = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .option(Option.createBuilder(boolean.class)
                                        .name(Text.translatable("viewmodel.category.advanced.group.general.function.rotZ"))
                                        .description(OptionDescription.of(Text.translatable("viewmodel.category.advanced.group.general.function.rotZ")))
                                        .binding(defaults.rotAnimOffZ, () -> config.rotAnimOffZ, newVal -> config.rotAnimOffZ = newVal)
                                        .controller(TickBoxControllerBuilder::create)
                                        .build())
                                .build())
                        .build())
        )).generateScreen(parent);
    }
}